apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mks-lineage-check-oct-9
  project: defaultproject
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.30.4
    location: mumbai-in
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: mks-sample-cp-node
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.104.215
      roles:
      - Worker
      - ControlPlane
  type: mks
