apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-rctl-apply-dedicated-ha-v3
  project: defaultproject
spec:
  blueprint:
    name: minimal-openebs
    version: v1
  cloudCredentials: vasu-mks-ssh-01
  config:
    autoApproveNodes: true
    dedicatedControlPlane: true
    highAvailability: true
    kubernetesVersion: v1.28.9
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-c-3
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.117.35
      roles:
      - ControlPlane
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-1
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.75.4
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-3
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.122.229
      roles:
      - Worker
      ssh:
        ipAddress: 10.12.122.229
        port: "22"
        privateKeyPath: /home/ubuntu/oci
        username: ubuntu
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-2
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.5.203
      roles:
      - Worker
      ssh:
        ipAddress: 10.12.5.203
        port: "22"
        privateKeyPath: /home/ubuntu/oci
        username: ubuntu
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-c-2
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.39.130
      roles:
      - ControlPlane
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-c-1
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.52.53
      roles:
      - ControlPlane
  type: mks
