apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-rctl-apply-v3-scale-test
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: vasu-mks-ssh-01
  config:
    autoApproveNodes: true
    dedicatedControlPlane: true
    highAvailability: true
    kubernetesVersion: v1.29.4
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-c-2
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.6.161
      roles:
      - ControlPlane
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-11
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.29.164
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-4
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.113.47
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-c-3
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.113.103
      roles:
      - ControlPlane
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-3
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.38.194
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-7
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.40.36
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-21
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.17.251
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-22
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.56.99
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-13
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.40.120
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-12
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.52.40
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-14
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.64.103
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-18
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.37.96
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-17
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.119.111
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-8
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.91.124
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-24
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.20.152
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-26
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.113.205
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-1
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.91.140
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-2
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.74.5
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-10
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.121.238
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-6
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.46.232
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-19
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.23.208
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-9
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.8.6
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-23
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.95.238
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-c-1
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.60.237
      roles:
      - ControlPlane
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-20
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.79.165
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-25
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.7.125
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-27
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.83.192
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-5
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.20.224
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-16
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.89.158
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-salt-scale-delay-w-15
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.40.240
      roles:
      - Worker
  type: mks
