apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-rctl-apply-v3-converged-ha
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: vasu-mks-ssh-01
  config:
    autoApproveNodes: true
    highAvailability: true
    kubernetesVersion: v1.28.9
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-1
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.48.231
      roles:
      - ControlPlane
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-2
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.101.17
      roles:
      - ControlPlane
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-3
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.96.235
      roles:
      - ControlPlane
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-1
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.16.15
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-2
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.98.97
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-3
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.35.106
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-4
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.50.209
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-5
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.70.60
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-6
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.88.143
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-7
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.11.15
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-8
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.30.58
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-9
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.26.203
      roles:
      - Worker
  type: mks
