apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-gitsync-ha-101
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: latest
  cloudCredentials: vasu-mks-ssh-v4
  config:
    autoApproveNodes: true
    dedicatedMastersEnabled: true
    highAvailability: true
    kubernetesVersion: v1.28.5
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-1
      operatingSystem: Ubuntu20.04
      privateip: 10.12.39.91
      roles:
      - Master
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-2
      operatingSystem: Ubuntu20.04
      privateip: 10.12.7.67
      roles:
      - Master
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-3
      operatingSystem: Ubuntu20.04
      privateip: 10.12.42.128
      roles:
      - Master
    - arch: amd64
      hostname: vasu-mks-scale-w-tb
      operatingSystem: Ubuntu20.04
      privateip: 10.12.11.159
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-2
      operatingSystem: Ubuntu20.04
      privateip: 10.12.33.10
      roles:
      - Worker
  type: mks


  2024-04-05T13:36:26.787Z	INFO	generators/provisiontasksetgenerator.go:81	Starting task set generation for	{"edgeName": "vasu-mks-gitsync-ha-101", "desiredConfig": {"apiVersion":"infra.k8smgmt.io/v3","kind":"Cluster","metadata":{"name":"vasu-mks-gitsync-ha-101","project":"defaultproject"},"spec":{"type":"mks","blueprint":"minimal","blueprintversion":"latest","cloudprovider":"vasu-mks-ssh-v4","config":{"location":"sanjose-us","kubernetesVersion":"v1.28.5","kubernetesUpgrade":{},"autoApproveNodes":true,"highAvailability":true,"dedicatedMastersEnabled":true,"network":{"cni":{"name":"Calico","version":"3.26.1"},"podSubnet":"10.244.0.0/16","serviceSubnet":"10.96.0.0/12"},"nodes":[{"hostname":"vasu-mks-scale-c-tb-1","operatingSystem":"Ubuntu20.04","arch":"amd64","privateip":"10.12.39.91","roles":["Master"],"ssh":{}},{"hostname":"vasu-mks-scale-c-tb-2","operatingSystem":"Ubuntu20.04","arch":"amd64","privateip":"10.12.7.67","roles":["Master"],"ssh":{}},{"hostname":"vasu-mks-scale-c-tb-3","operatingSystem":"Ubuntu20.04","arch":"amd64","privateip":"10.12.42.128","roles":["Master"],"ssh":{}},{"hostname":"vasu-mks-scale-w-tb","operatingSystem":"Ubuntu20.04","arch":"amd64","privateip":"10.12.11.159","roles":["Worker"],"ssh":{}},{"hostname":"vasu-mks-scale-w-tb-2","operatingSystem":"Ubuntu20.04","arch":"amd64","privateip":"10.12.33.10","roles":["Master"],"ssh":{}}]}}}, "desiredConfigContent": "apiVersion: infra.k8smgmt.io/v3\nkind: Cluster\nmetadata:\n  name: vasu-mks-gitsync-ha-101\n  project: defaultproject\nspec:\n  blueprint: minimal\n  blueprintversion: latest\n  cloudprovider: vasu-mks-ssh-v4\n  config:\n    autoApproveNodes: true\n    dedicatedMastersEnabled: true\n    highAvailability: true\n    kubernetesUpgrade: {}\n    kubernetesVersion: v1.28.5\n    location: sanjose-us\n    network:\n      cni:\n        name: Calico\n        version: 3.26.1\n      podSubnet: 10.244.0.0/16\n      serviceSubnet: 10.96.0.0/12\n    nodes:\n    - arch: amd64\n      hostname: vasu-mks-scale-c-tb-1\n      operatingSystem: Ubuntu20.04\n      privateip: 10.12.39.91\n      roles:\n      - Master\n    - arch: amd64\n      hostname: vasu-mks-scale-c-tb-2\n      operatingSystem: Ubuntu20.04\n      privateip: 10.12.7.67\n      roles:\n      - Master\n    - arch: amd64\n      hostname: vasu-mks-scale-c-tb-3\n      operatingSystem: Ubuntu20.04\n      privateip: 10.12.42.128\n      roles:\n      - Master\n    - arch: amd64\n      hostname: vasu-mks-scale-w-tb\n      operatingSystem: Ubuntu20.04\n      privateip: 10.12.11.159\n      roles:\n      - Worker\n    - arch: amd64\n      hostname: vasu-mks-scale-w-tb-2\n      operatingSystem: Ubuntu20.04\n      privateip: 10.12.33.10\n      roles:\n      - Master\n    proxyConfig: {}\n  type: mks\n"}
