apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-gitsync-ha-001
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: vasu-mks-ssh-01
  config:
    autoApproveNodes: true
    dedicatedMastersEnabled: true
    highAvailability: true
    kubernetesVersion: v1.28.9
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-2
      operatingSystem: Ubuntu20.04
      privateip: 10.12.33.30
      roles:
      - Master
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-2
      operatingSystem: Ubuntu20.04
      privateip: 10.12.105.227
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-7
      labels:
        app: infra
      operatingSystem: Ubuntu20.04
      privateip: 10.12.110.50
      roles:
      - Worker
      taints:
      - effect: NoSchedule
        key: app
        value: infra
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-3
      operatingSystem: Ubuntu20.04
      privateip: 10.12.29.164
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-6
      labels:
        app: infra
      operatingSystem: Ubuntu20.04
      privateip: 10.12.101.223
      roles:
      - Worker
      taints:
      - effect: NoSchedule
        key: app
        value: infra
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-3
      operatingSystem: Ubuntu20.04
      privateip: 10.12.118.110
      roles:
      - Master
    - arch: amd64
      hostname: vasu-mks-scale-c-tb-1
      operatingSystem: Ubuntu20.04
      privateip: 10.12.87.186
      roles:
      - Master
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-5
      operatingSystem: Ubuntu20.04
      privateip: 10.12.106.74
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-4
      operatingSystem: Ubuntu20.04
      privateip: 10.12.106.155
      roles:
      - Worker
    - arch: amd64
      hostname: vasu-mks-scale-w-tb-1
      operatingSystem: Ubuntu20.04
      privateip: 10.12.44.34
      roles:
      - Worker
  systemComponentsPlacement:
    nodeSelector:
      app: infra
    tolerations:
    - effect: NoSchedule
      key: app
      operator: Equal
      value: infra
  type: mks