apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-bitnami
  project: vasu-project
spec:
  endpoint: https://charts.bitnami.com/bitnami
  options: {}
  type: Helm
status:
  projects:
  - projectId: 72dg7g2
    repositoryId: 5m1o6y2
  webhookConfig:
    webhookSecret: c00a7581eb1432c3420e1ae4784fbb0b11e56932ca87efb01453b0796aba09c6
    webhookURL: https://qc-console.stage.rafay.dev/v2/config/webhook/repository/5m1o6y2
