apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: vasu-mks-git-repo
  project: defaultproject
spec:
  agents:
  - name: vasu-mks-agent-july-26
  credentials:
    password: sealed://credentials.password
    username: vasu@rafay.co
  endpoint: https://github.com/RafaySystems/mks-gitsync-playground.git
  options:
    insecure: true
  secret:
    name: file://artifacts/vasu-mks-git-repo/sealed-secret.yaml
  type: Git
status:
  agents:
  - id: q6kn4ml
    name: vasu-mks-agent-july-26
  projects:
  - projectId: rx28oml
    repositoryId: 7dkgjkx
  webhookConfig:
    webhookSecret: e1aa2b6809d2994c30ab6f21d0037585dc099a7b85b319cd79743b6715cb42c6
    webhookURL: https://console-vasu-mks-v3.dev.rafay-edge.net/v2/config/webhook/repository/7dkgjkx
