apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vasu-mks-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDPgPNb0XA6lT5vH9cVzOMWGO7szOL5AW3VDe1wF6H2H4Y8xdpAvtmg7TnLp7FClJi5DVwlPp+EpowjYYbkvdsJiUHwZm0brhsCyB64Ft8f8YboN0GAaK3bGTGzY4sLzDTZ31S/eCiVEPigk5e9sgltdi8f4S1N2JkrwVNVukZtmy4211Q5SrSt78U6rqQ7tWusz6+5rw7qii0Q79dErvMeitQ+FzRYU9ufdhyKmd7cqz+PPfDcKmyVDRI0DEKvNlzyLhbtEuV2jv0O0v34ipLkYdp+XKRWVHKE6HeTCqoSPW0zmeEtPCbzrWBWtLIm803gyAli71lh7jDr4egVgPqxJjsQpjtM1qBUGB0+t+9ucUqYxlYfhYC3MYDm4ID/7cUThHIVTMCME3e6wqsXz6CvEHLt9MK9kk4=
  template:
    metadata:
      creationTimestamp: null
      name: vasu-mks-git-repo
      namespace: default

