apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vasu-mks-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDHzskWJsPq6ksmgErTEAiJumEEzh2ZtwkyVP0bPKX/rv7Amq+fHbCe02sejqOyYKKpG5+7Un2kEF+w9/nTkWzynf3KCICOIe5c3qFhMlK0OkfJUhCTTvRhiD5s3+WA+BC6bUAAue3bm4T2XeUxwBMktWLpcD2RBn1BOOlwgQ4y/dz5d7wyxez8073u5HzPMt5Aekcvl11b4DEN5ZA4frBntDbyjUG4PQUEQfq4u8VlJJgiPHYHbx+bRiRAZMQZO7c/nd6SN6v+SeBEHAGlOYFWaVXDh9AsFkFzynIIE8+Ygbf8NHBl0NuREfmAq/VJdUWY/YvA8NgQxo4RP8hcHFFaWeO38FDFIaAqk3TUHDYUm2bXUp2H85q2nNxMTMLEtW1RhqGIBOBFXi3V/NaStI35cgRwN3ZlzTs=
  template:
    metadata:
      creationTimestamp: null
      name: vasu-mks-git-repo
      namespace: default

