apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vasu-mks-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDHv4vcMOJJa0Ee+2mESmBuf4M6Otav6tuVX8AtIHBAh0l3+CdguRP7Y3G6SMviQ19aiIOdE9RZRrTRbBAQash5PaWyQDM6PZrH5DaK0G0Avn8M6zorpHf9yBzj6+VOgJE6upAsH1UwHldzv17bobTMNeJCc9NwnygCKppV7SJoc4PSOeBpueplflPyqjV7/sBKz74l7BG0jbESEj+1dakgVKgV5cbhkDPvC7kH//4mLr9FclXJh2rLFIc4ZJCoUlVuvxqiCg764APEIJSH1uwe6tnIL9PG7nknHs0AOZ55irlZ/F6tfyrCmcklg40/3+BAD7pdn5KI8ekwuK4ngnpq+mk3tJeJvDB3JZRIqxPIqOzzFJO+vMAraaqhDzY1OR1EERnlVm1BkiWhh10rW//bsDvND29kJoE=
  template:
    metadata:
      creationTimestamp: null
      name: vasu-mks-git-repo
      namespace: default

