apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vasu-mks-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBFJQym3f0Qx07isLImN8cdeqi4o1CPqMMuHsqLMvFvTB6AIX4CXam28Yd1Omb8jtBI3CQXf7CEJQ+FBVuRW+itPrzEi99jnp+va7DSNP3szvS5qmGyzqOc/bdJUTx7+6gJOpCfZXO6oe4cUeW1+tXNOp0KlcjGtb0vmW/5xFs4aYsoHdj4f/oF59S/0JGbYka51SS8Kx8KCMZlm3/+wPur0SnhDT2Rcd5/9KzH/h7Vk55qBmBCpKBV7vnpnAA1UUbDItisTtGP+s7vQcvA3lFHLdDA9kP/s1L20gFX/u77Iy0qR+xyQAzoc+9c2fd+GgzUJLPDSpGIcGLhz9HRu89tGksrfkAcWIoQQDsOwORAoOM1e0Zjs2toeOtq90ExYyDihDSHgDUJAWJC88MjY8m35zMpXxLUhpY=
  template:
    metadata:
      creationTimestamp: null
      name: vasu-mks-git-repo
      namespace: default

