apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vasu-mks-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDVSw3snL5GNSTy3j6ydz9ES9PE48+fMtVLSeDsfNONSyaK+aYXIAaPLzffo4EtD+abQzSLLdc8otsOgDT4JKU48r1NVrztJbxD80mrLcdoAhkvZe0vM/x6MmcDy72TypSUY/+lbyOCQDqPWtQeF55ah4j32XL3XroyW3pprJGUDydD/3cPBoNwoZ4PDIxyLJtprOUQaj2lClTTMhBs1anhGJ4hXREtFIamGaSCEQM0wewH/dWqDF9yQd+tibb0wQe7DN0KHfXQcrcHnK0H2ea4Ca6EMAhz5gicVFwyjQSwpM9m3+I7OjUEDkc/qvNV3ZCKuW9p+N7ePMSesYBKb7NeeZY+jchOCL9OkT0zcrk91ISVAiSdtWW3ndJ3h6/ucUG+E2AoWZlo5VQij7FOrGrwpMZ5NEBeeqk=
  template:
    metadata:
      creationTimestamp: null
      name: vasu-mks-git-repo
      namespace: default

