apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: mks-systemsync-pipeline
  project: defaultproject
spec:
  active: true
  stages:
  - config:
      committerEmail: vasu@rafay.co
      destinationRepo:
        path:
          name: demo
        repository: vasu-mks-git-repo
        revision: main
      includedResources:
      - name: Blueprint
      - name: Cluster
      - name: Agent
      - name: Pipeline
      - name: Repository
      systemToGitSync: true
    name: vasu-mks-system-sync-stage
    type: SystemSync
  triggers:
  - config:
      repo:
        provider: Github
        repository: vasu-mks-git-repo
        revision: main
    name: mks-test-trigger
    type: Webhook
