apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: mks-systemsync-pipeline
  project: defaultproject
spec:
  active: true
  stages:
  - config:
      approvers:
      - userName: vasu@rafay.co
      timeout: 0s
      type: Email
    name: approval-stage
    next:
    - name: vasu-mks-system-sync-stage
    type: Approval
  - config:
      committerEmail: vasu@rafay.co
      destinationRepo:
        path:
          name: demo
        repository: vasu-mks-git-repo
        revision: main
      gitToSystemSync: true
      includedResources:
      - name: Cluster
      sourceRepo:
        path:
          name: demo
        repository: vasu-mks-git-repo
        revision: main
      systemToGitSync: true
    name: vasu-mks-system-sync-stage
    type: SystemSync
  triggers:
  - config:
      repo:
        provider: Github
        repository: vasu-mks-git-repo
        revision: main
    name: mks-test-trigger
    type: Webhook
