apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-test-relay-agent
  project: vasu-project
spec:
  blueprint:
    name: default
  config:
    kubernetesVersion: v1.26.5
    location: mumbai-in
    network:
      cni:
        name: Calico
        version: 3.24.5
      ipv6:
        podSubnet: 2001:db8:42:0::/56
        serviceSubnet: 2001:db8:42:1::/112
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: rahul-z-mks-scale-c-g
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.81.32
      roles:
      - Worker
      - ControlPlane
      ssh: {}
  type: mks
