apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-gitsync-july-22
  project: vasu-project
spec:
  blueprint:
    name: minimal-with-openebs
    version: v1
  cloudCredentials: vasu-mks-ssh
  config:
    autoApproveNodes: true
    kubernetesVersion: v1.28.9
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-mks-v3-qc-c
      labels:
        app: infra
        infra: "true"
        test: app
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.11.158
      roles:
      - ControlPlane
      - Worker
    - arch: amd64
      hostname: vasu-mks-v3-qc-w
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.52.58
      roles:
      - Worker
  type: mks
