apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-test-new-salt
  project: vasu-project
spec:
  blueprint:
    name: minimal
  config:
    kubernetesVersion: v1.25.8
    location: aws/ap-south-1
    network:
      cni:
        name: Calico
        version: 3.24.5
      ipv6:
        podSubnet: 2001:db8:42:0::/56
        serviceSubnet: 2001:db8:42:1::/112
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-mks-scale-c
      operatingSystem: Ubuntu22.04
      privateIP: 10.12.110.75
      roles:
      - Worker
      - ControlPlane
      ssh: {}
  type: mks
