apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vasu-mks-check-upgrade-nov-09
  project: vasu-project
spec:
  blueprint:
    name: minimal
  config:
    kubernetesVersion: v1.28.1
    location: mumbai-in
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vasu-z-mks-scale-c-g
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.59.12
      roles:
      - ControlPlane
      - Worker
      ssh: {}
    - arch: amd64
      hostname: vasu-z-mks-scale-w-g-1
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.123.163
      roles:
      - Worker
      ssh: {}
    - arch: amd64
      hostname: vasu-z-mks-scale-w-g-2
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.33.95
      roles:
      - Worker
      ssh: {}
    - arch: amd64
      hostname: vasu-z-mks-scale-w-g-3
      operatingSystem: Ubuntu20.04
      privateIP: 10.12.5.134
      roles:
      - Worker
      ssh: {}
  type: mks
