apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rafay-aws-eaas
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AQAuoEUhetMfe+XwSIxtvbIpZkWcpfL3mzJfu24IfuZoqlnbmZCRvPODfYgh4CV1P31kFm6XBQiDismsC6nmgv2/pwy8JtotkAoBrINS38aeB4vi8d2J6UcG0VpYh+0eM6N7SuT2qwYo3FLXbsWh6BoaMzcAB0f8jde20R+Qi0b0QghWmrMin9ix0dOjVKmodrhv9AGfbOwDk8MNOMjGzZi7sxMpaWjh1MgSkpW0ZIYC33EnaZ5T73UqB2uvcEPX+sd/titX/BmJZmhq4TqLLiVPBeQe2Q2/nQxgHEeZ9RE18Xo3SrZDCgqWXPEZW2pxD/qZiF9nLUyKSIJxFbhwQzxjcI6Rk67duwXPgh+BxN7wnBzQuy65avZnZI3iICk5SqB0UTYi
    AWS_SECRET_ACCESS_KEY: AQAZWoYmUh3w3t2Epwrjv6VhOX1PvCkCHpvBgoROcCQKv8YojJa43yTWb9ZzDe+mJ+UlVeT/0dqcVNtDt8jrd4uLoD4KMhNvsHNP3Twki9XtC3LGzTJywcUbbwQ6DdvkqFg0q/BzNaXi6Ij+YhQVLT3Ru3rq4WnBWX+uSqnih8qzEtpmnPbqtz4yabQjJ7Fwy0/cMnsAFoz+BJgcNezpQ2OUendoOqb5BNQE21iuaoi/rSjwvUQIAx1RyTwxaBvw5u2dsx/iT0odsYhxC1b5bhP4gSy4p6pXzw5i477BlpAprC1VvFoQGr7L3RjEgRpEe293h3heJV0yqvmWMKPIZJypzE14oCs0QC8a68y4M/Q8L//cIZZReyaWC0FPfHa8x89CkMYIBe7pDaRD1pVa45opvYDstGiMybs=
  template:
    metadata:
      creationTimestamp: null
      name: rafay-aws-eaas
      namespace: default

