apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: test-vasu
  project: vasu-project
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  networkPolicyParams: {}
  resourceQuotas: {}
