apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: rafay-aws-eaas
  project: eaas
spec:
  envs:
  - key: AWS_ACCESS_KEY_ID
    sensitive: true
    value: sealed://AWS_ACCESS_KEY_ID
  - key: AWS_SECRET_ACCESS_KEY
    sensitive: true
    value: sealed://AWS_SECRET_ACCESS_KEY
  secret:
    name: file://artifacts/rafay-aws-eaas/sealed-secret.yaml
