apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: minimal-openebs
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.8.0
  defaultAddons:
    enableIngress: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
