apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rauto-blueprint-7126281
  project: defaultproject
spec:
  base:
    name: default
    version: 2.7.0
  customAddons:
  - name: rauto-addon-1884946
    version: v1
  - name: rauto-addon-172569
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
