apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-route53-delegation-zones
  project: eaas
spec:
  agents:
  - name: eaas-agent-oct-10
  contexts:
  - name: rafay-aws-eaas
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-route53
    name: eaas-repo-eaas
  variables:
  - name: create
    options:
      description: Whether to create Route53 zone
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: zones
    options:
      description: Map of Route53 zone parameters
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  - name: tags
    options:
      description: Tags added to all zones. Will take precedence over tags from the
        'zones' variable
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
