apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rafay-aws-route53-delegation-resolver-rule-associations
  project: eaas
spec:
  agents:
  - name: eaas-agent-oct-10
  contexts:
  - name: rafay-aws-eaas
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/rafay-aws-resources/terraform/aws-route53
    name: eaas-repo-eaas
  variables:
  - name: create
    options:
      description: Whether to create Route53 Resolver rule associations
      override:
        type: allowed
    value: "true"
    valueType: hcl
  - name: vpc_id
    options:
      description: Default VPC ID for all the Route53 Resolver rule associations
      override:
        type: allowed
    value: "null"
    valueType: hcl
  - name: resolver_rule_associations
    options:
      description: Map of Route53 Resolver rule associations parameters
      override:
        type: allowed
    value: '{}'
    valueType: hcl
  version: v1
  versionState: active
