apiVersion: infra.k8smgmt.io/v3
kind: Credentials
metadata:
  name: test-001
  project: defaultproject
spec:
  credentials:
    type: sshRemote # specific to mks /sshLocal
    user: ubuntu
    privateKey: sealed://credentials.privateKey
    port: "22"
    agents:
    - vasu-agent
  provider: mks # inroducing mks
  secret:
    name: file://artifacts/test-001/sealed-secret.yaml
  type: ClusterProvisioning