apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-bitnami
  project: eaas
spec:
  endpoint: https://charts.bitnami.com/bitnami
  options: {}
  type: Helm
status:
  projects:
  - projectId: q6kn4ml
    repositoryId: dk69gk1
  webhookConfig:
    webhookSecret: d0b0490c9da759e366ecf77a0ef128fb7b5c99c444ae8ffc910afabeac17ff3e
    webhookURL: https://console-vasu-mks-v3.dev.rafay-edge.net/v2/config/webhook/repository/dk69gk1
